### ISSUE TITLE
Osu Restful issue on webpage loading

### ISSUE THREAD

**Issue by carlobolla** [OsuSync/OsuDataDistributeRestful#4]
Whenever i try to connect to the webage displaying RTPPD data, i get this issue and nothing is shown except for the blue background:

(Sync is started as Admin and plugins are installed correctly, config has been edited and such)

```
[16:05:54] System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.MissingFieldException: Impossibile trovare il campo 'RealTimePPDisplayer.Displayer.HitCountTuple.RealTimeMaxCombo'.
   in OsuDataDistributeRestful.Api.RtppdApis.MakeHitCount(Nullable`1 tuple)
   in OsuDataDistributeRestful.Api.RtppdApis.GetHitCount(Int32 id)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   in System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   in System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   in OsuDataDistributeRestful.Server.ApiServer.CallMethod(Method method, ParamCollection params)
   in OsuDataDistributeRestful.Server.ApiServer.OnResponse(HttpListenerRequest request, HttpListenerResponse response)
```
Sorry, my system is in Italian...

**Comment by KedamaOvO** [comment]
Can you tell me the version of ODDR and RTPPD?

**Comment by carlobolla** [comment]
ODDR is on v0.3.0 and RTPPD is on v1.5.0

**Comment by KedamaOvO** [comment]
fixed. try ODDR v0.3.2
https://github.com/OsuSync/OsuDataDistributeRestful/releases/download/v0.3.2/OsuDataDistribute-Restful-0.3.2.zip

**Comment by carlobolla** [comment]
Tested v0.3.2
Now http://localhost:10800/api/rtppd/pp gets the right data and it's populated. In the HTML folder, the bpm file works, but the pp monitor still shows the blue background only.

Thanks for your hard work btw! :)

![Screenshot](https://user-images.githubusercontent.com/14152206/45104945-72aa1e00-b133-11e8-8ec7-140afbd2d9dc.png)

**Comment by KedamaOvO** [comment]
Please tell me your PPFormat and HitCountFormat.

**Comment by carlobolla** [comment]
```
PPFormat=${rtpp}pp => ${maxpp}
HitCountFormat=${n100@0}x100 ${n50@0}x50 ${nmiss@0}xMiss
```

**Comment by KedamaOvO** [comment]
I updated rtpp.html, please download it again 0.3.2

**Comment by carlobolla** [comment]
Works perfectly now! Thanks a lot for your time and work on this project! ;)

**Comment by carlobolla** [comment]
Oh and just a thing, @KedamaOvO could you notify when the rttp.html file is updated on your repo, please?

**Comment by KedamaOvO** [comment]
This seems unlikely.
Github did not provide this notification.
